Fix docs for constructorof due to changes in julia v1.12
The binding rules changed at the REPL in julia v1.12 breaking this
document test.  See the error message below.

```
julia> struct T{A,B}
                  a::A
                  b::B
              end

julia> Raven.constructorof(T{Int,Int})
ERROR: UndefVarError: `T` not defined in `Main`
Suggestion: define the const at top-level before running function that uses it (stricter Julia v1.12+ rule).
Note: the binding state changed since the error occurred (was: 11, now: 0).
Stacktrace:
 [1] #s75#6
   @ ~/research/code/julia/Raven/src/flatten.jl:138 [inlined]
 [2] var"#s75#6"(T::Any, ::Any, ::Any)
   @ Raven ./none:0
 [3] (::Core.GeneratedFunctionStub)(::UInt64, ::Method, ::Any, ::Vararg{Any})
   @ Base ./expr.jl:1694
 [4] top-level scope
   @ REPL[3]:1
```

Thus, we just change the example to work.